# Grafana Datasource Configuration for InfluxDB
# Place this file in: grafana/datasources/influxdb.yml

apiVersion: 1

datasources:
  - name: InfluxDB-Fitbit
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: true
    orgId: 1
    version: 2
    jsonData:
      # InfluxDB v2 configuration
      version: Flux
      organization: fitbit
      defaultBucket: fitbit
      httpMode: POST
      
      # Query settings
      maxSeries: 1000
      httpHeaderName1: "User-Agent"
      
      # Alerting settings
      timeInterval: "10s"
      
      # Health monitoring specific settings
      customQueryParameters: 
        - name: "precision"
          value: "ms"
    
    secureJsonData:
      # InfluxDB token (set via environment variable)
      token: "${INFLUX_TOKEN}"
      httpHeaderValue1: "Grafana-Fitbit-Dashboard/2.0"

  # Optional: Separate datasource for different retention policies
  - name: InfluxDB-Fitbit-Archive
    type: influxdb  
    access: proxy
    url: http://influxdb:8086
    editable: true
    orgId: 1
    version: 2
    jsonData:
      version: Flux
      organization: fitbit
      defaultBucket: fitbit-archive
      httpMode: POST
      maxSeries: 5000
      timeInterval: "1m"
    
    secureJsonData:
      token: "${INFLUX_TOKEN}"

  # Optional: Prometheus for system metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
    orgId: 1
    isDefault: false
    jsonData:
      httpMethod: POST
      queryTimeout: "60s"
      timeInterval: "15s"

  # Optional: Loki for log aggregation  
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    orgId: 1
    isDefault: false
    jsonData:
      maxLines: 1000
      timeout: "60s"

deleteDatasources:
  # Clean up any old datasources
  - name: InfluxDB_v1
    orgId: 1
  - name: TestData
    orgId: 1